name: Deploy

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  ftp-deploy:
    name: FTP Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v3

    - name: Yarn Install
      uses: DerYeger/yarn-setup-action@master
      with:
        node-version: 14
      
    - name: Yarn Build
      run: yarn build
    
    - name: Upload files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: ${{ secrets.FTP_DIRECTORY }}
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/vendor/**